env: "local"
rpc:
  address: ":50051"
database:
  uri: "321"
  external_storage_path: "C:\Users\melik\GolandProjects\goph-keeper\external_store"
  migrations_path: "C:\Users\melik\GolandProjects\goph-keeper\internal\repository\migrations"
  max_cons: 1
logging:
  level: "debug"
otp:
  algorithm: "SHA1"
  digits: 6
  period: 30